name: why workflow 

on:
  push:
    branches:
      - main
      
jobs:
  Dags:
    name: 'projects/Sync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run content check script
        run: |
          if grep -q 'projects/lead-score' hello.txt; then
            echo "Running docker file"
            # Add your Docker command here
          else
            echo "String 'projects/lead-score' not found in hello.txt"
          fi
