name: why workflow 

on:
  push:
    branches:
      - main
      
jobs:
  Dags:
    name: 'projects/Sync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run content check script
        run: |
          if grep -q 'projects/lead-score' hello.txt || echo "${{ github.event.head_commit.message }}" | grep -q 'Dockerfile-lead-score'; then
            echo "Running docker file"
            # Add your Docker command here
          else
            echo "Content check failed. Skipping Docker file execution."
          fi
