name: why workflow

on:
  push:
    branches:
      - main
      
jobs:
  Dags:
    name: 'projects/Sync'
    if: contains(check_changed_files('hello.txt'), 'projects/lead-score')
    runs-on: ubuntu-latest
    steps:
      - name: Running Docker file
        run: echo "running docker file"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
