name: why workflow 

on:
  push:
    branches:
      - main
      
jobs:
  Dags:
    name: 'projects/Sync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run content check script
        if: contains(github.event.head_commit.message, 'Dockerfile-lead-score') || grep -q 'projects/lead-score' hello.txt
        run: |
          echo running docker file 
